name: Deploy to Docker Hub

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  test:
    uses: ljmerza/misc-actions/.github/workflows/python-tests.yml@v1
    with:
      python-version: "3.11"
      coverage-source: "frigate_plate_recognizer"

  deploy_latest_to_docker:
    name: Deploy Latest Tag to Docker Hub
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build and push
        uses: ljmerza/misc-actions/actions/docker-build-push@v1
        with:
          image-name: ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKERHUB_REPO }}
          registry: docker.io
          registry-username: ${{ secrets.DOCKERHUB_USERNAME }}
          registry-password: ${{ secrets.DOCKERHUB_TOKEN }}
          tags: |
            type=raw,value=latest
