name: Create Release

on:
  workflow_dispatch:
  push:
    tags:
      - '*'

jobs:
  test:
    uses: ljmerza/misc-actions/.github/workflows/python-tests.yml@v1
    with:
      python-version: "3.11"
      coverage-source: "frigate_plate_recognizer"

  release:
    name: Create Release
    needs: test
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Extract Tag Name
        id: tag_name
        run: echo "::set-output name=tag::$(echo ${GITHUB_REF#refs/tags/})"

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.tag_name.outputs.tag }}
          release_name: Release ${{ steps.tag_name.outputs.tag }}
          draft: false
          prerelease: false

  docker_tag:
    name: Create Docker Tag
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build and push tag
        uses: ljmerza/misc-actions/actions/docker-build-push@v1
        with:
          image-name: ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKERHUB_REPO }}
          registry: docker.io
          registry-username: ${{ secrets.DOCKERHUB_USERNAME }}
          registry-password: ${{ secrets.DOCKERHUB_TOKEN }}
          tags: |
            type=ref,event=tag
